### PR TITLE
docs(README): input is mutated by normalize-package-data

### LINKED ISSUE #12: input argument object is mutated
hi all,

It looks like `get-pkg-repo` is mutating the input argument object. Proof is here: https://runkit.com/embed/wvvbqgicfj9v

Basically, I assigned a real package.json into a variable and cloned it into a second-one. Then ran first through `get-pkg-repo` feeding it as argument. That was enough for it not to be `deepEqual` to second-one afterwards.

Either let's **fix this** or **state in the readme** that input args will be **mutated**. This causes issues during unit tests and people should be aware of it.

cheers

### PR DESCRIPTION
**Pull request by hbetts**
Fixes #12.

### CODE REVIEW

**Comment by hbetts** [comment]
cc @revelt

**Comment by hbetts** [comment]
@stevemao looks like CI isn't passing because tests are executed on older versions of Node that don't support the features of this code base.

Suggestions for moving forward?

**Comment by hbetts** [comment]
I committed 7c618bce3a87601a5c58c3f13b3af3a2dec87e48 to the `master` branch to update the Node versions in Travis CI.

Looks like a dependency of `get-pkg-repo` changed their minimum version of Node supported.

**Comment by revelt** [comment]
Good job. Node versions less than v.4 are deprecated anyway and 4 seems to pass fine. It's ES6 arrows in `supports-color`.

**Pull request merged**
